name: Unity Continuous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test Unity Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform: [StandaloneLinux64, StandaloneWindows64, StandaloneOSX]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Cache Unity Files
        uses: actions/cache@v4
        with:
          path: SealTeam7/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.0.34f1
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: SealTeam7
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}